name: publish-docker-images

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.SCW_REGISTRY }}
          username: ${{ secrets.SCW_ACCESS_KEY }}
          password: ${{ secrets.SCW_SECRET_KEY }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./backup-db
          tags: ${{ secrets.SCW_REGISTRY }}/mesads/backup-db:latest
